### PR TITLE
Integration | Tiny ECS

### PR DESCRIPTION
**Pull request by blackbone**
so this integration was created by @andreakarasho 's request to check TinyECS

In common i facing some issues so need some advices or changes from author.

Current Problems:

- [x] `World.EntityCount` (at TinyEcsContext.cs:14) returns capacity of entities sparse set, not actual entities count.
> it needed for tests to ensure all integrity checks are passing to get valid results.
- [x] placeholder for next issues

### CODE REVIEW

**Comment by andreakarasho** [comment]
Hello, thank you for the test integration!
In TinyEcs components are entities, so I think the approach to follow is the same of the Flecs.NET implementation.

**Comment by blackbone** [comment]
> Hello, thank you for the test integration! In TinyEcs components are entities, so I think the approach to follow is the same of the Flecs.NET implementation.

There's some problems i have pointed in first comment need to be solved before push integration.

The blocking problem for now is to possibility to get **actual** entity count. Because it returns 8 on empty world in version 1.3.0 from NuGet. It would be nice if you point me the correct API for it or fix it if possible.

**Comment by andreakarasho** [comment]
> The blocking problem for now is to possibility to get actual entity count. Because it returns 8 on empty world in version 1.3.0 from NuGet. It would be nice if you point me the correct API for it or fix it if possible.

Yeah I meant to go with the same approach you use with Flecs.NET instead of use `TinyEcs.World.EntityCount`:
https://github.com/blackbone/other-ecs-benchmarks/blob/af592360fbfd0a24526a86ec51328c89a3fe52b2/Benchmark.FlecsNET/FlecsNETContext.cs#L19

The reason is because TinyEcs creates an entity when initializing a component [components are entities]:
https://github.com/andreakarasho/TinyEcs/blob/3bbede073904a16fbca63e954a1f52a86509cf63/src/World.cs#L48-L61

Infact there are 8 built-in components initialized on startup: https://github.com/andreakarasho/TinyEcs/blob/3bbede073904a16fbca63e954a1f52a86509cf63/src/World.Public.cs#L28-L35

**Comment by blackbone** [comment]
@andreakarasho i have managed to implement all stuff but faced one more issue.

So the issues is like bevy systems are conflicting with manual deffered usage which causing stackoverflow on tests.

stack trace for it looking kind of that

```
 at TinyEcs.World.QueryRaw(System.Collections.Immutable.ImmutableArray`1<TinyEcs.QueryTerm>)
   at TinyEcs.World.Delete(TinyEcs.EcsID)
   at TinyEcs.World.Merge()
   at TinyEcs.World.EndDeferred()
   at TinyEcs.Query.Each(TinyEcs.QueryFilterDelegateWithEntity)
   at TinyEcs.World.Delete(TinyEcs.EcsID)
   at TinyEcs.World.Merge()
   at TinyEcs.World.EndDeferred()
   at TinyEcs.Query.Each(TinyEcs.QueryFilterDelegateWithEntity)
   at TinyEcs.World.Delete(TinyEcs.EcsID)
   at TinyEcs.World.Merge()
   at TinyEcs.World.EndDeferred()
   at TinyEcs.Query.Each(TinyEcs.QueryFilterDelegateWithEntity)
   at TinyEcs.World.Delete(TinyEcs.EcsID)
   at TinyEcs.World.Merge()
   at TinyEcs.World.EndDeferred()
   at TinyEcs.Query.Each(TinyEcs.QueryFilterDelegateWithEntity)
   at TinyEcs.World.Delete(TinyEcs.EcsID)
... and so on
```

can you pls verify current immplementation so i can move further?

**Comment by andreakarasho** [comment]
> @andreakarasho i have managed to implement all stuff but faced one more issue.
> 
> So the issues is like bevy systems are conflicting with manual deffered usage which causing stackoverflow on tests.
> 
> stack trace for it looking kind of that
> 
> ```
>  at TinyEcs.World.QueryRaw(System.Collections.Immutable.ImmutableArray`1<TinyEcs.QueryTerm>)
>    at TinyEcs.World.Delete(TinyEcs.EcsID)
>    at TinyEcs.World.Merge()
>    at TinyEcs.World.EndDeferred()
>    at TinyEcs.Query.Each(TinyEcs.QueryFilterDelegateWithEntity)
>    at TinyEcs.World.Delete(TinyEcs.EcsID)
>    at TinyEcs.World.Merge()
>    at TinyEcs.World.EndDeferred()
>    at TinyEcs.Query.Each(TinyEcs.QueryFilterDelegateWithEntity)
>    at TinyEcs.World.Delete(TinyEcs.EcsID)
>    at TinyEcs.World.Merge()
>    at TinyEcs.World.EndDeferred()
>    at TinyEcs.Query.Each(TinyEcs.QueryFilterDelegateWithEntity)
>    at TinyEcs.World.Delete(TinyEcs.EcsID)
>    at TinyEcs.World.Merge()
>    at TinyEcs.World.EndDeferred()
>    at TinyEcs.Query.Each(TinyEcs.QueryFilterDelegateWithEntity)
>    at TinyEcs.World.Delete(TinyEcs.EcsID)
> ... and so on
> ```
> 
> can you pls verify current immplementation so i can move further?

I pulled your latest changes and executed all tests with no issues:
```Test summary: total: 711; failed: 0; succeeded: 711; skipped: 0; duration: 13,2s```

**Pull request merged**
